### ISSUE TITLE
xml binding tck documentation issues

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jaxb-tck#19]
* no release notes, spec/javadoc assertions in the tck distribution - all others I checked do have these, so I believe that at least release notes should be added
* user guide:
  * uses `javax.xml.bind` packages, should be `jakarta.xml.bind`
  * talks about `XML Binding 2.3`, should be `XML Binding 3.0` instead
  * copyright footer should probably be updated to `2018, 2020`
  * FAQ A3 should probably update `<TS_HOME>/lib/jaxb_tck23.jtx` to `<TS_HOME>/lib/jaxb_tck30.jtx`

This is copied from https://github.com/eclipse-ee4j/jakartaee-tck/issues/436 

@edbratt @gurunrao

**Comment by Tomas-Kraus** [comment]
Well, I opened user guide and most of the setup text is based on running the configuration GUI and setting properties based on the long tab in chapter **4.1.2 XML Binding-Specific Configuration Settings**.
So I downloaded latest jakarta-xml-binding-tck-3.0.0.zip and did following steps:
```
unzip jakarta-xml-binding-tck-3.0.0.zip
java -jar JAXB-TCK-3.0.jar 
export TS_HOME=/data/tck/tmp/JAXB-TCK-3.0
cd ${TS_HOME}/bin && ant gui
```
And last command failed with
```
bash: cd: /data/tck/tmp/JAXB-TCK-3.0/bin: No such file or directory
```
I checked extracted file structure and yes, JAXB-TCK-3.0/bin is really missing in the bundle.
So whole user guide which is based on and script in ${TS_HOME}/bin and usage of JavaTest GUI does not make sense now.

Current JAXB TCK jobs are based on `docker/run_jaxbtck.sh` shell script in git repository which is using pre-configured setup in `${TS_HOME}/lib/javasoft-multiJVM.jti` which works fine with EE4J JAXB RI 3.0.0 releases, but this is just internal solution. Customers can't access it.

JAXB TCK bundle needs working setup before we can start working on user guide.

**Comment by Tomas-Kraus** [comment]
I found old TCK user guide from Sun: [JAXB-TCK_Users_Guide.pdf](https://github.com/eclipse-ee4j/jaxb-tck/files/5141538/JAXB-TCK_Users_Guide.pdf)

**Comment by m0mus** [comment]
@alwin-joseph or @gurunrao can you help with the issue @Tomas-Kraus found? Shall we just remove this chapter or just keep a properties list with some description? I guess that these properties can be updated in some configuration files using a text editor.

**Comment by Tomas-Kraus** [comment]
Config GUI can be started another way:
```
export TS_HOME=/where/is/JAXB-TCK-3.
cd $TS_HOME
java -jar lib/javatest.jar -newDesktop
```
But it also does not work. Looks like it can't find testsuite config.

**Comment by gurunrao** [comment]
@m0mus - I have created new bundle here - https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck-grao/job/build-changes/lastSuccessfulBuild/artifact/bundles/xml-binding-tck-3.0.0.zip for getting started.
We are currently working based on old user guide.

**Comment by gurunrao** [comment]
@Tomas-Kraus Please followow these steps for running the JAXB TCK:
export WORKSPACE=$PWD

wget https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck-grao/job/build-changes/lastSuccessfulBuild/artifact/bundles/xml-binding-tck-3.0.0.zip -O $WORKSPACE/xml-binding-tck.zip && unzip $WORKSPACE/xml-binding-tck.zip

wget https://ci.eclipse.org/jaxb-impl/job/jaxb-ri-master-build/lastSuccessfulBuild/artifact/jaxb-ri/bundles/ri/target/jaxb-ri.zip -O $WORKSPACE/jaxb-ri.zip && unzip -o $WORKSPACE/jaxb-ri.zip
 
wget https://repo1.maven.org/maven2/jakarta/activation/jakarta.activation-api/2.0.0-RC3/jakarta.activation-api-2.0.0-RC3.jar -O $WORKSPACE/jakarta.activation-api.jar

wget https://repo1.maven.org/maven2/org/checkerframework/checker/3.5.0/checker-3.5.0.jar -O ${WORKSPACE}/checker.jar

open JAXB-TCK-3.0/testsuite.jtt and set "finder" to "com.sun.javatest.finder.BinaryTestFinder -binary ./testsuite.jtd"


###################### start tests  command line

$JAVA_HOME/bin/java -jar ${WORKSPACE}/JAXB-TCK-3.0/lib/javatest.jar -batch -testsuite ${WORKSPACE}/JAXB-TCK-3.0 -open ${WORKSPACE}/JAXB-TCK-3.0/lib/javasoft-multiJVM.jti -workdir -create ${WORKSPACE}/batch-multiJVM/work -set jck.env.jaxb.xsd_compiler.skipValidationOptional Yes -set jck.env.jaxb.xsd_compiler.testCompile.xjcCmd "/bin/sh ${WORKSPACE}/JAXB-TCK-3.0/linux/bin/xjc.sh" -set jck.env.jaxb.schemagen.run.jxcCmd "/bin/sh ${WORKSPACE}/JAXB-TCK-3.0/linux/bin/schemagen.sh" -set jck.env.jaxb.testExecute.otherEnvVars "JAVA_HOME=/opt/jdk1.8.0_191 JAXB_HOME=${WORKSPACE}/jaxb-ri JAXB_ENDORSED=${WORKSPACE}/jaxb-ri/mod/jakarta.xml.bind-api.jar" -set jck.env.jaxb.classes.jaxbClasses "${WORKSPACE}/checker.jar ${WORKSPACE}/jaxb-ri/mod/jakarta.xml.bind-api.jar ${WORKSPACE}/jaxb-ri/mod/jaxb-impl.jar ${WORKSPACE}/jaxb-ri/mod/jaxb-jxc.jar ${WORKSPACE}/jaxb-ri/mod/jakarta.activation.jar" -set jck.env.jaxb.classes.needJaxbClasses Yes -runtests

**Comment by Tomas-Kraus** [comment]
I started working on user guide updates. My work in progress PR is here: https://github.com/eclipse-ee4j/jaxb-tck/pull/29

**Comment by lukasj** [comment]
this one is fixed
