### ISSUE TITLE
TCK User’s Guide for Technology Implementors issues

### ISSUE THREAD

**Issue by rfelcman** [eclipse-ee4j/jaxb-tck#32]
This is summary of issues in "TCK User’s Guide for Technology Implementors" document.
Issues described there was found during EclipseLink MOXy (JAXB Implementation) testing.
Page numbers bellow are from output pdf document.
1. Page 8: "Exclude List file, `${TS_HOME}/lib/jaxb_tck30.jtx`" file doesn't exist. There is `jaxb_tck23.jtx` only.
2. Page 22: Wrong bundle name: `jakarta-xml-binding-tck-3.0.0.zip` . Currently there is available only `xml-binding-tck-3.0.0.zip` .
3. Page 24: ? `$JAXWS_HOME/bin` ? Maybe `$JAXB_HOME/bin` should be there, but `$JAXB_HOME/bin` directory doesn't exist it's not needed there.
4. Page 25: I'd like highlight there, that JAXB TCK search JAXB implementation by `META-INF/services/jakarta.xml.bind.JAXBContext` and `META-INF/services/jakarta.xml.bind.JAXBContextFactory` files. In EclipseLink MOXy is PR for this https://github.com/eclipse-ee4j/eclipselink/pull/906

**Comment by lukasj** [comment]
fixed already
