### ISSUE TITLE
wrong content of the tck zip

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jaxb-tck#36]
when I unzip the jakarta-xml-binding-tck-3.0.0.zip file, what I see is:

* missing top level directory like in other tcks (others contain `<spec-name-version>` folder while jaxb tck unzips everything into current folder)
* current `JAXB-TCK-3.0` folder contains subfolder `?`
* it looks like `JAXB-TCK-3.0.jar` installer can be removed since its content seems to be already expanded

**Comment by gurunrao** [comment]
@RohitKumarJain - can you look into the content mismatch highlighted by lukas.

**Comment by RohitKumarJain** [comment]
@gurunrao @lukasj , I am looking into it. Will update with my findings on the same.

**Comment by RohitKumarJain** [comment]
@gurunrao @lukasj @alwin-joseph , when I am testing the generated bundle directory structure in my local machine it does not contain "?" as part of "XML-binding-tck-3.0.0.zip". 
Even when I am trying to extract in my Windows machine, again I don't see "?" folder. 

While when I am trying to download in my Linux machine (wget https://ci.eclipse.org/jakartaee-tck/job/rjain-jaxb-tck/job/master/6/artifact/bundles/xml-binding-tck-3.0.0.zip) I am observing "?" folder is getting generated. 

I tried to debug it further but not sure why "?" folder is generating? Can anyone please help to fix this? 

Attaching the screenshots in the documents while investigating this issue.
[Analysis.docx](https://github.com/eclipse-ee4j/jaxb-tck/files/5341857/Analysis.docx)

**Comment by lukasj** [comment]
#41 should fix remaining issues (including `?` directory)

**Comment by RohitKumarJain** [comment]
@lukasj , I just checked the generated bundle as part of https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/63/ and also tried to test the latest bundle from https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-xml-binding-tck-3.0.0.zip. My finding is below:

- "?" still appearing as part of the bundle.

- As per the new bundle structure, now we are moving one level up with the content of  XMLB-TCK-3.0.

**Comment by lukasj** [comment]
@RohitKumarJain 

* wrt bundle structure - it's now follows other TCK bundles

* wrt `?` folder - can you try to alter your job to only build the tck bundle (no need to wait 8 hours for test runs), archive `jaxb-tck-build/installer-classes.lst` and `jaxb-tck-build/unzip.log` files and modify `ant clean dist_eftl` call in `build_jaxbtck.sh` to `ant clean dist_eftl` and rerun your job? that could show us from where the `?` folder is comming...

**Comment by alwin-joseph** [comment]
> @RohitKumarJain
> 
>     * wrt bundle structure - it now follows other TCK bundles
> 
>     * wrt `?` folder - can you try to alter your job to only build the tck bundle (no need to wait 8 hours for test runs), archive `jaxb-tck-build/installer-classes.lst` and `jaxb-tck-build/unzip.log` files and modify `ant clean dist_eftl` call in `build_jaxbtck.sh` to `ant -v clean dist_eftl` and rerun your job? that could show us from where the `?` folder is comming...

https://github.com/eclipse-ee4j/jaxb-tck/pull/42 should resolve the ? folder. Tested it in a separate job. Awaiting the completion of https://ci.eclipse.org/jakartaee-tck/job/eftl-jaxb-tck-build-run/13/ to refresh the staged bundle.

**Comment by alwin-joseph** [comment]
> > @RohitKumarJain
> > ```
> > * wrt bundle structure - it now follows other TCK bundles
> > 
> > * wrt `?` folder - can you try to alter your job to only build the tck bundle (no need to wait 8 hours for test runs), archive `jaxb-tck-build/installer-classes.lst` and `jaxb-tck-build/unzip.log` files and modify `ant clean dist_eftl` call in `build_jaxbtck.sh` to `ant -v clean dist_eftl` and rerun your job? that could show us from where the `?` folder is comming...
> > ```
> 
> #42 should remove the ? folder. Tested it in a separate job. Awaiting the completion of https://ci.eclipse.org/jakartaee-tck/job/eftl-jaxb-tck-build-run/13/ to refresh the staged bundle.

https://ci.eclipse.org/jakartaee-tck/job/eftl-jaxb-tck-build-run/14 was run instead of above job and https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-xml-binding-tck-3.0.0.zip was refreshed. Can you please verify if we can promote this bundle. I see no "?" folder.

**Comment by RohitKumarJain** [comment]
> > > @RohitKumarJain
> > > ```
> > > * wrt bundle structure - it now follows other TCK bundles
> > > 
> > > * wrt `?` folder - can you try to alter your job to only build the tck bundle (no need to wait 8 hours for test runs), archive `jaxb-tck-build/installer-classes.lst` and `jaxb-tck-build/unzip.log` files and modify `ant clean dist_eftl` call in `build_jaxbtck.sh` to `ant -v clean dist_eftl` and rerun your job? that could show us from where the `?` folder is comming...
> > > ```
> > 
> > 
> > #42 should remove the ? folder. Tested it in a separate job. Awaiting the completion of https://ci.eclipse.org/jakartaee-tck/job/eftl-jaxb-tck-build-run/13/ to refresh the staged bundle.
> 
> https://ci.eclipse.org/jakartaee-tck/job/eftl-jaxb-tck-build-run/14 was run instead of above job and https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-xml-binding-tck-3.0.0.zip was refreshed. Can you please verify if we can promote this bundle. I see no "?" folder.

@alwin-joseph , I have just verified the structure while taking the .zip from https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-xml-binding-tck-3.0.0.zip. The structure looks good to me, and thanks for making the fix for "?". According to me, we can promote the bundle.
@lukasj @gurunrao , requesting if you also see it once before promoting the bundle.

**Comment by lukasj** [comment]
yup, all problems are fixed now. Go ahead and promote the TCK binary, please. Thanks!

**Comment by alwin-joseph** [comment]
> yup, all problems are fixed now. Go ahead and promote the TCK binary, please. Thanks!

Thanks. I have promoted the TCK binary to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-binding-tck-3.0.0.zip .
