### ISSUE TITLE
Need 3.0.1 release of TCK to support Java 11 / EE 9.1

### ISSUE THREAD

**Issue by brideck** [eclipse-ee4j/jaxb-tck#54]
Up until some time this week, it looked like there was a planned 3.0.1 release of the XML Binding TCK, but it has since vanished from the staging area for EE 9.1 (https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/).  From talking to Scott Marlow (EE TCK Lead), it appears that a recent discussion stated that the extant 3.0.0 release of the TCK is sufficient to support EE 9.1.

However, I can confirm from my own testing that this is not the case.  Any attempt to use the 3.0.0 TCK with Java 11 leads to a failure in the signature test with "Unsupported Java version".  The 3.0.1 release of the TCK should be restored so that it can be used for EE 9.1 certification with Java 11.

**Comment by gurunrao** [comment]
@brideck  - We are waiting on confirmation from @senivam on runs with 3.0.0  TCK and JDK 11 and GF 6.1

**Comment by lukasj** [comment]
we still need 3.0.1 to fix the wrong pointer to spec mailing list...

**Comment by gurunrao** [comment]
@lukas @scottkurz  @brideck - I have started https://ci.eclipse.org/jakartaee-tck/job/eftl-jaxb-tck-build-run/ and https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck-nightly-build-run/ for build + run + staging of jaxb bundles

**Comment by scottmarlow** [comment]
If anyone has problems passing the signature tests, you may of missed the following step before starting the agent:
```
cd xml-binding-tck/tests/api/signaturetest
```

^ ensures the signature map files can be found relative to the above folder.
