### ISSUE TITLE
Service release of xml-binding-tck-3.0.2.zip for Java SE 17

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jaxb-tck#59]
https://ci.eclipse.org/jakartaee-tck/job/eftl-jaxbtck-certification/15 verified that the XML Binding TCK [jakarta-xml-binding-tck-3.0.2.zip](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-binding-tck-3.0.2.zip) passed tests with https://download.eclipse.org/ee4j/glassfish/glassfish-6.1.0.zip on Java SE 11. 

I'm going to verify that  [jakarta-xml-binding-tck-3.0.2.zip](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-binding-tck-3.0.2.zip) also works with WildFly on Java SE 17.

As per the [TCK Process 1.1 document](https://jakarta.ee/committees/specification/tckprocess/) `A service release may update tests to work with newer Java SE versions.` which allows jakarta-xml-binding-tck-3.0.2.zip to be officially released for addressing https://github.com/eclipse-ee4j/jaxb-tck/issues/57.

jakarta-xml-binding-tck-3.0.2.zip will need to be released by the Jakarta EE Specification committee.  https://jakarta.ee/specifications/xml-binding/3.0 needs to be updated similar to https://github.com/jakartaee/specifications/pull/410 except https://download.eclipse.org/jakartaee/xml-binding/3.0 needs `jakarta-xml-binding-tck-3.0.2.zip` so that compatible implementations can certify on Java SE 17.

**Comment by scottmarlow** [comment]
@lukasj as lead of XML Binding, could you please send email to jakarta.ee-spec.committee@eclipse.org requesting that http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-binding-tck-3.0.2.zip be signed and copied to https://download.eclipse.org/jakartaee/xml-binding/3.0/jakarta-xml-binding-tck-3.0.2.zip.

I'll update this issue after completing my testing of WildFly + http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-binding-tck-3.0.2.zip with Java SE 17

**Comment by lukasj** [comment]
...I'm waiting for your results. None of us want to re-do this in case you see failures...

**Comment by scottmarlow** [comment]
> ...I'm waiting for your results. None of us want to re-do this in case you see failures...

Ah, sorry, all tests passed!
`Pass: 24,628 Fail: 0 Error: 0 Not-Run: 0`

**Comment by lukasj** [comment]
> Your message has been rejected...

that does not seem to be the right mailing list...

**Comment by lukasj** [comment]
btw that list is not public and I'm not a member, so there must be either different list or way...

**Comment by scottmarlow** [comment]
> btw that list is not public and I'm not a member, so there must be either different list or way...
Sorry, please try jakarta.ee-spec@eclipse.org which is for https://accounts.eclipse.org/mailing-list/jakarta.ee-spec

**Comment by lukasj** [comment]
I believe this is done
