### ISSUE TITLE
TCK Challenge for 16 tests failing due to www.w3.org redirect from http to https

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jaxb-tck#78]
The same tests were passing previous to the change from http to https.

For background see articles:
- https://www.w3.org/blog/2022/08/https-redirection-observations/#comment-117406
- https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/

The XML Binding 4.0 TCK tests that are failing now that previously passed before the www.w3.org started redirecting `http` requests to `https`.

For background see https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/ + https://www.w3.org/blog/2022/08/https-redirection-observations

Tests that are failing now that previously passed before the https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/ change:

1. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0001.jtr
2. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0002.jtr    
3. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0003.jtr 
4. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0001.jtr     
5. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0002.jtr 
6. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0003.jtr 
7. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/property_fields/XmlMimeType/src01_testCase0001.jtr
8. api/jakarta_xml/bind/JAXBContext/java2schema/CustomizedMapping/property_fields/XmlMimeType/src01_testCase0002.jtr
9. java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0001.jtr
10. java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0002.jtr
11. java2schema/CustomizedMapping/packages/XmlAccessorType/srcInherit5_testCase0003.jtr
12. java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0001.jtr
13. java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0002.jtr
14. java2schema/CustomizedMapping/packages/XmlAccessorType/srcNone_testCase0003.jtr
15. java2schema/CustomizedMapping/property_fields/XmlMimeType/src01_testCase0001.jtr
16. java2schema/CustomizedMapping/property_fields/XmlMimeType/src01_testCase0002.jtr 

[Failing test jtr files are archived here via failure_jtr.zip](https://github.com/eclipse-ee4j/jaxb-tck/files/9536776/failure_jtr.zip).

[GlassFish 7.0.0-M8](https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-M8.zip) also fails as well as per https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/175/

CC @alwin-joseph @gurunrao @arjantijms

**Comment by scottmarlow** [comment]
To verify that the XML Binding 4.0 TCK test failures still occur, @gurunrao  started https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/176/ and https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/177/ are the latest runs of XML Binding TCK with GF 7 M8.  Thanks Guru!

**Comment by scottmarlow** [comment]
Output from last Friday's (September 9, 2022) [GF test run](https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/175/testReport/junit/api.jakarta_xml.bind.JAXBContext.java2schema.CustomizedMapping.packages.XmlAccessorType.srcInherit5/html/testCase0001/) is copied to https://gist.github.com/scottmarlow/da62aa4596b2fb159a8a8515efbc17dc

**Comment by gurunrao** [comment]
@scottmarlow - https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/176/ and https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/177/ are failing. 
The GF 7 M8 certification run https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/174/ and https://ci.eclipse.org/jakartaee-tck/job/jaxb-tck/job/master/173/, which are run ~20 days ago have passed.

**Comment by jimma** [comment]
@gurunrao  That's expected. Before this w3 website http->https redirect change, tests are all passed. After the redirect, there will be 16 test failures.

**Comment by gurunrao** [comment]
> @gurunrao That's expected. Before this w3 website http->https redirect change, tests are all passed. After the redirect, there will be 16 test failures.

The tests passed with http -> https redict change before was my point.

**Comment by scottmarlow** [comment]
Could one of the committers please add the `challenge` label to this issue.  

https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Jakarta-EE-10.0-TCK-results has been updated to include the failing 16 XML Binding TCK tests.  

From https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org:
> Redirecting to https on all of www.w3.org
> W3C’s main web site [www.w3.org](https://www.w3.org/) has been available via https for over a decade, but until now we have not been redirecting all requests to https as is commonly done on most other sites.
>
> The primary reason for this is that we wanted to avoid causing issues for software requesting machine-readable resources from [www.w3.org](https://www.w3.org/) such as HTML DTDs, XML Schemas, and namespace documents.
> We believe enough time has passed for most such software to have been updated to handle redirects and https, so we are planning to start redirecting all requests received over http to https within a month or two.
> ...

As we can all read, any `http` requests will be redirected to `https` which is the likely cause of the 16 GlassFish 7 M8 TCK failures that contain messages like this:
```
compileSchema: Failed. Fatal error:http://www.w3.org/2005/05/xmlmime(1,1): Premature end of file.
STATUS:Failed.test cases: 1; all failed; first test case failure: compileSchema
----------out2:(1/76)----------
Fatal Error: http://www.w3.org/2005/05/xmlmime(1,1): Premature end of file.
result: Failed. test cases: 1; all failed; first test case failure: compileSchema


test result: Failed. test cases: 1; all failed; first test case failure: compileSchema
```

The quickest correction for these failures would be excluding the 16 tests and releasing a https://download.eclipse.org/jakartaee/xml-binding/4.0/jakarta-xml-binding-tck-4.0.1.zip with the 16 tests excluded.  The alternative would take longer and involve updating the 16 tests to not use `http` references to the www.w3.org website (or something like that).

**Comment by jimma** [comment]
@lukasj  I didn't see 4.0.1 is available from https://repo.maven.apache.org/maven2/org/glassfish/jaxb/jaxb-runtime.  Is it available somewhere ?

**Comment by jimma** [comment]
@lukasj I see the jaxb-ri 4.0.1 artifact for this tck issue is still in stage : https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/jaxb/jaxb-core/4.0.1/.  Can it be released now ?

**Comment by lukasj** [comment]
@jimma this is not the right place for questions about RI
